### ISSUE TITLE
Error getting output back from Core; aborting

### ISSUE THREAD

**Issue by Kasperait** [Telefonica/Eternalblue-Doublepulsar-Metasploit#94]
When I try to scan for vulnerabilities on my computer, I do not write anything. I tried to use did not directly exploit eternalblue doblepulser. I got out the computer does not have antivirus and firewall.
P.S Sorry for not accurate translation, I do not know English

Here is a screenshot:
![Screenshot_2](https://user-images.githubusercontent.com/42416467/55562424-8be07080-56fc-11e9-887c-684edd3a0029.png)
![Screenshot_1](https://user-images.githubusercontent.com/42416467/55562430-900c8e00-56fc-11e9-92f3-1ba9a5391edb.png)

**Comment by PLEASEFORGETME2** [comment]
@Kasperait Your Windows 7 is maybe not vulnerable...

**Comment by GetRektBoy724** [comment]
> @Kasperait Your Windows 7 is maybe not vulnerable...

Yeah cause if your windows 7 is vulnerable....the output from the auxiliary was different

**Comment by ZhiboWong** [comment]
> @Kasperait Your Windows 7 is maybe not vulnerable...

When I use `auxiliary/scanner/smb/smb_ms17_010` to scan the rhost, feedback is Host is likely VULNERABLE to MS17-010!
But when I use `windows/smb/eternalblue_doublepulsar)` to exp the rhost , the feedback is [-] Error getting output back from Core; aborting...
I guess the reason why I can not exp the vulnerable rhost is because the rhost opens AV or FW. So what should I do?
